export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGING_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";

export const IS_AUTH = "IS_AUTH";

export const GET_LOGGED_IN = "GET_LOGGED_IN";
export const REQUEST_LOGGED_IN_SUCCESS = "REQUEST_LOGGED_IN_SUCCESS";
export const REQUEST_LOGGED_IN_FAILED = "REQUEST_LOGGED_IN_FAILED";
